name: Build

on: [push, pull_request]

jobs:
  theos-rootless:
    runs-on: macos-13

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Theos
        uses: Randomblock1/theos-action@v1

      - name: Build package
        run: |
          export PATH="/usr/local/opt/make/libexec/gnubin:$PATH"
          export PACKAGE_BUILDNAME=$(git rev-parse --short HEAD)-rootless
          make clean package THEOS_PACKAGE_SCHEME=rootless FINALPACKAGE=1

      - name: Upload package
        uses: actions/upload-artifact@v3
        with:
          path: ./packages/com.beeper.beepserv_*.deb
          name: phone-registration-provider
          if-no-files-found: error
  theos-rootful:
    runs-on: macos-11
    
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
    
      - name: Set up Theos
        uses: Randomblock1/theos-action@v1
    
      - name: Build package
        run: |
          export PATH="/usr/local/opt/make/libexec/gnubin:$PATH"
          export PACKAGE_BUILDNAME=$(git rev-parse --short HEAD)-rootful
          make clean package FINALPACKAGE=1
    
      - name: Upload package
        uses: actions/upload-artifact@v3
        with:
          path: ./packages/com.beeper.beepserv_*.deb
          name: phone-registration-provider
          if-no-files-found: error
